Footer Component criado
lucaoskaique/resgatemais pull request #19
Opened 2024-07-30 18:37 UTC by gabriel-chagas-albuquerque

O Componente Footer foi criado

2024-08-01 13:53 UTC, VFGarciaDev commented on src/components/Footer/index.tsx
Não precisa fazer a adição da font no Footer. A font será instalada de forma global e irá aplicar em todos os componentes automaticamente

2024-08-01 16:44 UTC, lucaoskaique requested changes

2024-08-01 16:44 UTC, lucaoskaique commented on src/pages/index.tsx
> +      <Footer />
```suggestion
     
```

2024-08-01 16:44 UTC, lucaoskaique commented on src/pages/index.tsx
> +import Footer from "@/components/Footer"
```suggestion

```

2024-08-01 16:44 UTC, lucaoskaique commented on src/components/Footer/index.tsx
> +const lexend_zetta = Lexend_Zetta({ subsets: ["latin"] })
```suggestion

```
como o victor falou

2024-08-06 01:16 UTC, lucaoskaique approved these changes

2024-08-06 01:17 UTC, lucaoskaique reviewed
🙏

2024-08-06 01:17 UTC, merged