feat: add global fontFamily
lucaoskaique/resgatemais pull request #22
Opened 2024-08-01 16:00 UTC by VFGarciaDev

## Mudanças realizadas

- Adição de fonte local em aspecto global
- Uso de `.variable' ao invés de `.className` (TailwindCSS)
- Adição das fontes na pasta assets/fonts

## Tipo de mudança

- [x] Nova funcionalidade

## Checklist:

- [ ] As modificações não geram novos logs de erro ou aviso (_warning_).
- [ ] Eu adicionei testes que provam que a correção ou novo recurso funciona conforme esperado.
- [ ] Tanto os novos testes quanto os antigos estão passando localmente.

2024-08-01 16:46 UTC, lucaoskaique requested changes
para add font no tailwind é https://tailwindcss.com/docs/font-family

2024-08-01 18:01 UTC, VFGarciaDev commented
Desculpa, mas não entendi o problema
Eu fiz a adição da fonte no Tailwind como uma extensão e apliquei ela no body principal pelo uso de variáveis. Ela foi configurada no tailwind e chamei ela para o index global do site

2024-08-05 14:57 UTC, lucaoskaique approved these changes

2024-08-05 14:57 UTC, lucaoskaique commented
Agora sim!

2024-08-05 14:57 UTC, merged