feat: create DonateSection component
lucaoskaique/resgatemais pull request #30
Opened 2024-08-07 18:49 UTC by gabriel-chagas-albuquerque

## Mudanças realizadas

- Foi criado o componente para a seção de doações

2024-08-07 21:38 UTC, VFGarciaDev commented
Nos commits realizados por mim, fiz as seguintes adições:
- Instalação das seguintes dependências:
  - clsx & tailwind-merge: ja foram instaladas no PR do botão tbm
  - embla-carousel: componente base utilizado para criação do Carrossel

![image](https://github.com/user-attachments/assets/91c4c448-ca20-4f35-ac6e-d40f8d8b5690)

- Criação do componente carrossel, com adição de props para:
  - adicionar as imagens
  - definir se terá AutoPlay
  - caso tenha AutoPlay, definir o tempo de rotação
![image](https://github.com/user-attachments/assets/addf3738-7fcb-43fb-a146-a12dc57d8616)

2024-08-08 10:59 UTC, VFGarciaDev requested changes
Remover alterações realizadas no componente "DonateImageCarousel"

2024-08-08 10:59 UTC, VFGarciaDev commented on src/components/donateSection/carousel/imageCarousel.tsx
O componente foi criado com props sem um valor definido de propósito, para mante-lo neutro e customizável: 
- autoplay: opção para escolherem se deixa automático ou não
- carouselImages: essa prop foi criada para fazer um '.map' de uma lista de conteúdo que será definido por elas e não por nós. O 'contentTemplate' foi usado no Storybook para nossa visualização

Por favor, remover as alterações realizadas nesse componente (pode manter o '?' usado no 'carouselImage')

2024-08-08 11:19 UTC, VFGarciaDev commented on src/components/donateSection/carousel/imageCarousel.tsx
Percebi que esqueci de adicionar um comando no Autoplay. Por favor, ao fazer as remoções solicitadas, adicionar o seguinte código: `stopOnInteraction: false` na linha 23, embaixo de "stopOnMouseEnter"
![image](https://github.com/user-attachments/assets/397f3b5a-3e37-4148-8343-8f0ab22b9461)

2024-08-12 11:40 UTC, VFGarciaDev approved these changes
Perfeito, muito obrigado!

2024-08-12 18:47 UTC, lucaoskaique approved these changes

2024-08-12 18:49 UTC, merged