31 aprimoramento e correção geral
lucaoskaique/resgatemais pull request #35
Opened 2024-08-19 16:26 UTC by VFGarciaDev

## Mudanças realizadas

- Padronização na nomeação de pastas (PascalCase) e de arquivos (index / camelCase)
- Organização dos componentes no Storybook e Adição de templates para melhor visualização
- Correção dos imports e exports
- Configuração da Paleta de cores do Tailwind
- Criação de um ThemeToggler com opção de Switch ou Hamburguer
- Correção de problemas do componente Carrossel
- Criação de um componente Media para ser utilizado no carrossel
  - opção de utilizar imagens ou vídeos

## Tipo de mudança

- [x] Padronização de arquivos
- [x] Nova funcionalidade

## Checklist:

- [x] As modificações não geram novos logs de erro ou aviso (_warning_).
- [ ] Eu adicionei testes que provam que a correção ou novo recurso funciona conforme esperado.
- [ ] Tanto os novos testes quanto os antigos estão passando localmente.

2024-08-19 16:39 UTC, lucaoskaique requested changes
some changes requested

2024-08-19 16:39 UTC, lucaoskaique commented on src/components/Carousel/emblaCarouselReact.tsx
>  type CarouselPlugin = UseCarouselParameters[1]
@VFGarciaDev  muito feio isso aqui kkk

faz assim 
import { EmblaCarouselType } from 'embla-carousel'

  const logSlidesInView = useCallback((emblaApi: EmblaCarouselType) => {
    console.log(emblaApi.slidesInView())
  }, [])

2024-08-19 16:39 UTC, lucaoskaique commented on src/components/Carousel/emblaCarouselReact.tsx
> +// EmblaCarouselNext.displayName = "EmblaCarouselNext"
deleta código comentado

2024-08-19 16:39 UTC, lucaoskaique commented on src/components/CarouselMedia/index.tsx
> +  vSrc,
nomear melhor as variaveis, devem ser explicitas

2024-08-19 16:39 UTC, lucaoskaique commented on src/components/Input/index.tsx
> +const RegisterEmail = ({
o nome da pasta ta INPUT e o nome do componente exportado ta RegisterEmail deve ser só Input.

2024-08-19 16:39 UTC, lucaoskaique commented on src/components/Navbar/index.tsx
> +        className="bg-color-red block rounded-[0.313rem] px-4 py-3 lg:hidden"
red ou highlight? tem que se decidir.

2024-08-19 16:39 UTC, lucaoskaique commented on src/components/ThemeToggler/togglers.tsx
> +export function SwitchToggle({ theme, setTheme }: ToggleProps) {
nome do arquivo inconscistente com a pasta

2024-08-20 00:21 UTC, VFGarciaDev commented on src/components/Carousel/emblaCarouselReact.tsx
> +// EmblaCarouselNext.displayName = "EmblaCarouselNext"
Esse código pretendemos usar para configurar o botão de trocar a media do carrossel, mas, por enquanto, deixei comentado para deixar apenas com autoplay

2024-08-20 23:42 UTC, VFGarciaDev commented on src/components/Input/index.tsx
> +const RegisterEmail = ({
Alterei o componente para "Newsletter", pois o componente era mais doq só o Input e segui o nome usado no Template criado por você

2024-08-20 23:43 UTC, VFGarciaDev commented on src/components/CarouselMedia/index.tsx
> +  vSrc,
Alterado apenas para "src"

2024-08-21 14:48 UTC, lucaoskaique requested changes

2024-08-21 14:48 UTC, lucaoskaique commented on src/components/Newsletter/index.tsx
> +        />
Se temos um componente de input padrão, porque nao ta sendo utilizado aqui?

2024-08-21 14:48 UTC, lucaoskaique commented on src/components/donateSection/index.tsx
Nomeia pra `SectionDonate` a pasta, letra maiúscula

2024-08-21 14:48 UTC, lucaoskaique commented on src/components/ui/Switch/index.tsx
Nomeia a pasta pra "SwitchToggle"

2024-08-21 14:48 UTC, lucaoskaique commented on src/pages/api/(templates)/template.ts
Não entendi o objectivo disso aqui

2024-08-21 14:48 UTC, lucaoskaique commented on src/pages/donate/(components)/DonateInfo/index.tsx
compoennte chama DonateInfo e a pasta deveria ser o mesmo

2024-08-21 14:48 UTC, lucaoskaique commented on src/pages/donate/(components)/DonateInfo/index.tsx
> +    <footer className="py-8 text-center dark:bg-background-secondary dark:text-secondary lg:py-16 lg:pl-20 lg:text-left">
trocaria de footer ja que nao é mais footer como pensavam

2024-08-21 14:48 UTC, lucaoskaique commented on src/pages/donate/(components)/Hero/index.tsx
Novamente componente com um nome e pasta com outro DonatePageHero, pra que ter varios Hero se pode fazer um que muda com props?

2024-08-21 14:48 UTC, lucaoskaique commented on src/pages/donate/index.tsx
Sempre maiuscula a primeira letra no nome da Pasta

2024-08-22 14:11 UTC, VFGarciaDev commented on src/components/Newsletter/index.tsx
> +        />
Houve um engano anteriormente. O componente que eu havia nomeado como "Input" não era apenas um input, mas era a seção Newsletter por completo, ou seja, esse componente "Newsletter" é exatamente o componente "Input" de antes. Não temos um componente só de Input, até pq esse só é usado uma vez até o momento

2024-08-22 14:14 UTC, VFGarciaDev commented on src/pages/donate/(components)/DonateInfo/index.tsx
Mas a pasta possui o mesmo nome.

2024-08-22 14:14 UTC, VFGarciaDev commented on src/pages/donate/(components)/DonateInfo/index.tsx
> +    <footer className="py-8 text-center dark:bg-background-secondary dark:text-secondary lg:py-16 lg:pl-20 lg:text-left">
Alterado para 'section'

2024-08-22 14:23 UTC, VFGarciaDev commented on src/pages/api/(templates)/template.ts
Criei essa pasta para importar todas as informações, que são usadas nas props dos componentes, e exporta-las com nome diferente e apenas de um local. Com o intuito de ter apenas uma importação nos componentes de Template do site

2024-08-22 14:43 UTC, VFGarciaDev commented on src/pages/donate/(components)/Hero/index.tsx
Não tinha o componente Hero pronto ainda. Porém também da para perceber que ambos são bem similares. Vou fazer os ajustes para termos apenas um componente Hero

2024-08-22 16:34 UTC, lucaoskaique commented on src/pages/api/(templates)/template.ts
Vou aprovar, mas não fez muito sentido

2024-08-22 20:11 UTC, lucaoskaique approved these changes

2024-08-22 20:11 UTC, merged