8 customização do tema
lucaoskaique/resgatemais pull request #9
Opened 2024-07-24 14:15 UTC by VFGarciaDev

## Mudanças realizadas

- Instalação da dependência "next-themes"
- Criação do contexto `theme-provider.tsx`
- Adição das paletas de cores para os temas
- Criação de um botão para alterar tema como teste

<img src="https://github.com/user-attachments/assets/086192b1-3dd8-4da9-9e6a-6737ef12dff6" width="300" height="300" />
<img src="https://github.com/user-attachments/assets/b93af263-0682-4f19-a9d9-1d575258f4ad" width="300" height="300" />

## Tipo de mudança

- [x] Nova funcionalidade

## Checklist:

- [ ] As modificações não geram novos logs de erro ou aviso (_warning_).
- [ ] Eu adicionei testes que provam que a correção ou novo recurso funciona conforme esperado.
- [ ] Tanto os novos testes quanto os antigos estão passando localmente.

2024-07-24 14:28 UTC, lucaoskaique commented
@VFGarciaDev nao precisa de useeffec 
https://egghead.io/blog/tailwindcss-dark-mode-nextjs-typography-prose

2024-07-24 14:29 UTC, lucaoskaique requested changes
@VFGarciaDev nao precisa de useeffec 
https://egghead.io/blog/tailwindcss-dark-mode-nextjs-typography-prose

2024-07-24 15:32 UTC, lucaoskaique commented
@VFGarciaDev quando finalizar clica para avaliar novamente o PR

2024-07-24 16:01 UTC, lucaoskaique commented
> Para fazer a troca de Temas sem o uso do hook `useEffect()` para alterar o 'data-mode', foi necessário a remoção do 'data-mode' na configuração do Tailwind. Caso contrário, o html fazia a troca da classe, mas o Tailwind não identificava a troca do tema e não alterava entre as paletas. Por isso havia feito a adição do hook

então talvez deixamos, tem ver se ta funcionanod no storybook

2024-07-24 19:40 UTC, lucaoskaique requested changes
funciona com o storybook?

2024-07-24 22:08 UTC, VFGarciaDev commented
Voltei o ´[data-mode="dark"]` para as configs do TailwindCSS, fiz a adição do `useEffect()` para alterar no html. 
O tema está funcionando normalmente tanto no 'run dev' quanto no storyBook, o único porém é que alguns componentes estão com uma cor já definida e o tema não consegue sobrepor. Nesse caso, teríamos que apagar apenas a estilização da cor de texto
Ex.
![image](https://github.com/user-attachments/assets/41e40bf4-e539-4b13-8899-1628c32c594c)
![image](https://github.com/user-attachments/assets/7e7764ab-98a9-4396-aa6f-4858146f6f28)

2024-07-25 14:50 UTC, lucaoskaique approved these changes

2024-07-25 14:50 UTC, merged